version: 2.1

jobs:
  build:
    docker:
      - image: node:20

    steps:
      - checkout

      # Add steps for building and testing your code

      - run:
          name: Install sshpass
          command: |
            apt-get update && apt-get install -y sshpass

      - run:
          name: Deploy to VPS
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              sshpass -p "${VPS_PASSWORD}" ssh -o StrictHostKeyChecking=no "${VPS_USER}"@"${VPS_IP}" 'export PATH="$HOME/.volta/bin:$PATH" && cd ${VPS_PROJECT_PATH} && make release-develop-with-pm2'
              # Additional deployment steps as needed
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop